# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8eb071cac97495fc02a17272a1edecbd733540a178458c355b2bacdb8712aa8c8df5354a1884275d1d117e7683bdda08ae0b45c73853fe01afa843a4a477b51e

test:
  secret_key_base: 491cceedfa615de331d79406464bc01dbdbf2200fea78ae98e4a319bd83a498733ce257dc32f9817c89b68e984bbcb9cc41ed0444c8a2e9909181d2f9330795a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
